// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyvNrS_qpzNSce_ruXkbhBcvyCDsHrZXg',
    appId: '1:1004588655115:web:e8e82e5b7ffefdf998dd0e',
    messagingSenderId: '1004588655115',
    projectId: 'event-hub-946a7',
    authDomain: 'event-hub-946a7.firebaseapp.com',
    storageBucket: 'event-hub-946a7.appspot.com',
    measurementId: 'G-08BH3R6FJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdXjfyaFKFHxKdThyTemRVLF7p73aQEQo',
    appId: '1:1004588655115:android:6bec490d7a44c03f98dd0e',
    messagingSenderId: '1004588655115',
    projectId: 'event-hub-946a7',
    storageBucket: 'event-hub-946a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjrRHfB5pLN2IckvWb8kSxzrBBCrVucxo',
    appId: '1:1004588655115:ios:78d23b4de832dda698dd0e',
    messagingSenderId: '1004588655115',
    projectId: 'event-hub-946a7',
    storageBucket: 'event-hub-946a7.appspot.com',
    iosClientId: '1004588655115-6t231dnu5aajv5ale5lo3k5sklf03tgo.apps.googleusercontent.com',
    iosBundleId: 'com.jlarger.eventhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjrRHfB5pLN2IckvWb8kSxzrBBCrVucxo',
    appId: '1:1004588655115:ios:78d23b4de832dda698dd0e',
    messagingSenderId: '1004588655115',
    projectId: 'event-hub-946a7',
    storageBucket: 'event-hub-946a7.appspot.com',
    iosClientId: '1004588655115-6t231dnu5aajv5ale5lo3k5sklf03tgo.apps.googleusercontent.com',
    iosBundleId: 'com.jlarger.eventhub',
  );
}
